FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage for a minimal nginx image
FROM nginx:latest

COPY --from=build /app/dist/users-management-angular/server /usr/share/nginx/html 
COPY --from=build /app/dist/users-management-angular/browser /usr/share/nginx/html

# Replace the default nginx configuration 
# COPY nginx.conf /etc/nginx/conf.d/default.conf 

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]